#####################################
###  회원가입                     ###  
#####################################
###
POST http://localhost:3100/api/auth/signup
Content-Type: application/json

{
  "email": "user01@example.com",
  "nickname": "user01",
  "password": "12345678"
}

#####################################
###  일반유저                     ###  
#####################################
###  로그인
POST http://localhost:3100/api/auth/login
Content-Type: application/json

{
  "email": "User1@example.com",
  "password": "12345678"
}

### 로그아웃 
POST http://localhost:3100/api/auth/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjksInJvbGUiOiJVc2VyIiwiaWF0IjoxNzMyMTYzNzkzLCJleHAiOjE3MzIxNjczOTN9.Vb9qBTi9_MGDYJLJYyWE2M1uSE_m6D8_CRH3St5_myI

### refresh-token
POST http://localhost:3100/api/auth/refresh-token
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjksInJvbGUiOiJVc2VyIiwiaWF0IjoxNzMyMTYzNzY3LCJleHAiOjE3MzIxNjczNjd9.DuzBM9XMVW9oTRrsoXGKfdG7z1uDAhMiU4k08hKbugg

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjksInJvbGUiOiJVc2VyIiwiaWF0IjoxNzMyMTYzNzY3LCJleHAiOjE3MzMzNzMzNjd9.AioUDPuFfFpF3E_jysxsqvfy9CM9wkLy8bJcNG2rTvY"
}

#####################################
###  Admin  권한                  ###  
#####################################
###  로그인
POST http://localhost:3100/api/auth/login
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "12345678"
}

###  admi 액션
GET http://localhost:3100/api/auth/admin-action
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjYsInJvbGUiOiJBZG1pbiIsImlhdCI6MTczMjA4MjkyOCwiZXhwIjoxNzMyMDg2NTI4fQ.4j8QYON6iAi7UmHkrgf6_frPR-brz1BqqesZuySjMi0


###
GET http://localhost:3100/api/auth/admin-action
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInJvbGUiOiJVc2VyIiwiaWF0IjoxNzMyMDgyOTY3LCJleHAiOjE3MzIwODY1Njd9.xX3KUp4mohuHNfIq7q_b25ke5_bKPuDUkxsdth8MUZY




